### ISSUE TITLE
請教個lib.framework的問題

### ISSUE THREAD

**Issue by QingwenL** [sfsheng0322/DroidSmall#3]
你好，我看了lib.framework發現裏邊動態代理對象爲什麽能夠強轉為 Message？
 求指點一下，謝謝！ 
      
      if (result != null && result.getClass() == Message.class) {
                        Message msg = (Message) result;
                        switch (msg.arg1) {
                            case MessageArg.ARG1.TOAST_MESSAGE:
                                break;
                            case MessageArg.ARG1.CALL_BACK_METHOD:
                                if (msg.obj == null || !(msg.obj instanceof String) || "".equals(msg.obj.toString().trim())) {
                                    msg.obj = method.getName() + "CallBack";
                                }
                            default:
                                break;
                        }
                        mMethodCallBack.sendMessage(msg);
                    }

**Comment by sunfusheng** [comment]
result 本来就是Message对象

**Comment by QingwenL** [comment]
但是 result 本身不是個 BaseControl麽？ 

   private void generateControl(Class clazz) {
        Type type = clazz.getGenericSuperclass(); //获得带有泛型的父类
        if (type instanceof ParameterizedType) {
            ParameterizedType p = (ParameterizedType) type; //获得参数化类型，即泛型
            Type[] arrayClasses = p.getActualTypeArguments(); //获取参数化类型的数组，泛型可能有多个

            for (Type item : arrayClasses) {
                if (item instanceof Class) {
                    Class<T> tClass = (Class<T>) item;

                    if (tClass.equals(BaseControl.class) || (tClass.getSuperclass() != null && tClass.getSuperclass().equals(BaseControl.class))) {
                        messageProxy = new MessageProxy(mHandler);
                        mControl = ControlFactory.getControlInstance(tClass, messageProxy);
                        mModel = new ModelMap();
                        mControl.setModel(mModel);
                        return;
                    }
                }
            }
        }
    }
